[package]
name = "rust_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_engine"
crate-type = ["cdylib"]

[dependencies]
hashbrown = "0.14.2"
pyo3 = { version = "0.20.0", features = ["extension-module"] }
